name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: nightly
          version-type: strict
          rebar3-version: "3"
          # elixir-version: "1.15.4"

      - name: Check client
        run: |
          cd client
          gleam deps download
          gleam test
          gleam format --check src test

      - name: Check engine
        run: |
          cd server
          gleam deps download
          gleam test
          gleam format --check src test
          
